// esbuild settings for the plugin's MCP server (src/mcp), bundled into one file
// that the Claude Code, Codex and Claude Desktop packages run with `node`.
import { readFileSync } from 'node:fs'

const { version } = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'))

export const PLUGIN_BUNDLE = 'plugins/parallax/server/parallax-mcp.cjs'

export const pluginBuildOptions = {
  entryPoints: ['src/mcp/main.ts'],
  outfile: PLUGIN_BUNDLE,
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node20',
  minify: true,
  legalComments: 'eof',
  define: { __APP_VERSION__: JSON.stringify(version) },
  banner: { js: `// Parallax ${version} MCP server. Generated by scripts/build-plugin.mjs from src/mcp; don't edit.` },
  logLevel: 'warning',
}
